# Generated by Django 3.2.4 on 2021-06-29 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0003_publication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
