# Generated by Django 3.2.4 on 2021-06-29 21:02

from django.db import migrations, models
import postsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0005_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='img',
            field=models.ImageField(upload_to=postsapp.models.file_path),
        ),
    ]
